export const ProjectData = [
  { name: "FlakMe",
    github: "github link",
    demo: "demo link",
    data: "date",
    about: "about content",
    gif: "demo gif",
    mainphoto: "http://i.imgur.com/026drWB.png",
    photos:["photo 1", "photo 2"]
  },
  { name: "FlakMe",
    github: "github link",
    demo: "demo link",
    data: "date",
    about: "about content",
    gif: "demo gif",
    mainphoto: "main photo url",
    photos:["photo 1", "photo 2"]
  },
  { name: "FlakMe",
    github: "github link",
    demo: "demo link",
    data: "date",
    about: "about content",
    gif: "demo gif",
    mainphoto: "main photo url",
    photos:["photo 1", "photo 2"]
  },
  { name: "FlakMe",
    github: "github link",
    demo: "demo link",
    data: "date",
    about: "about content",
    gif: "demo gif",
    mainphoto: "main photo url",
    photos:["photo 1", "photo 2"]
  },
  { name: "FlakMe",
    github: "github link",
    demo: "demo link",
    data: "date",
    about: "about content",
    gif: "demo gif",
    mainphoto: "main photo url",
    photos:["photo 1", "photo 2"]
  },
  { name: "FlakMe",
    github: "github link",
    demo: "demo link",
    data: "date",
    about: "about content",
    gif: "demo gif",
    mainphoto: "main photo url",
    photos:["photo 1", "photo 2"]
  },
  { name: "FlakMe",
    github: "github link",
    demo: "demo link",
    data: "date",
    about: "about content",
    gif: "demo gif",
    mainphoto: "main photo url",
    photos:["photo 1", "photo 2"]
  },
  { name: "FlakMe",
    github: "github link",
    demo: "demo link",
    data: "date",
    about: "about content",
    gif: "demo gif",
    mainphoto: "main photo url",
    photos:["photo 1", "photo 2"]
  },
  { name: "FlakMe",
    github: "github link",
    demo: "demo link",
    data: "date",
    about: "about content",
    gif: "demo gif",
    mainphoto: "main photo url",
    photos:["photo 1", "photo 2"]
  },
  { name: "FlakMe",
    github: "github link",
    demo: "demo link",
    data: "date",
    about: "about content",
    gif: "demo gif",
    mainphoto: "main photo url",
    photos:["photo 1", "photo 2"]
  }
]
